definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store
  services:
    docker: 
      memory: 1024

pipelines:
  default:
    - step:
        name: Install, lint, build and test
        services:
          - docker
        # runs-on:
        #   - self.hosted
        #   - linux.arm64
        # image: olliecaine/ultimate-app-nvm-20-pnpm-10:1.0
        script:
          - docker build . -f Dockerfile.grok.node -t ci
          - docker image ls
          - >
            docker run --rm
            -v ${PWD}/.pnpm-store:/root/.pnpm-store
            -v ${PWD}:/app
            -w /app ci sh -c 'pnpm install --frozen-lockfile && pnpm run lint && pnpm run build && pnpm run test'
        caches:
          - pnpm
          - docker