definitions:
  caches:
    pnpm: .pnpm-store
    turbo: .turbo

pipelines:
  default:
    - step:
        name: Install & Health Check
        timeout: 10  
        caches:
          - pnpm
          - turbo
        services:
          - docker  
        size: 8x
        script:
          - mkdir -p .pnpm-store .turbo
          - chmod -R 777 .pnpm-store .turbo
          - |
            docker run --rm \
              -w /app \
              -v $BITBUCKET_CLONE_DIR/.pnpm-store:/app/.pnpm-store \
              -v $BITBUCKET_CLONE_DIR/.turbo:/app/.turbo \
              -v ${PWD}:/app \
              $(docker build . -q) \
              sh -c 'pnpm install --frozen-lockfile && pnpm run lint && pnpm run build'
