pipelines:
  default:
    - step:
        name: PNPM install & health check
        image: ubuntu:latest
        caches:
          - node
          - pnpm
          - turbo
        script:
          - apt-get update && apt-get install -y curl
          - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          - apt-get install -y nodejs
          - npm install -g pnpm@8.15.3
          - pnpm install --frozen-lockfile
          - pnpm lint
          # - pnpm test
          - pnpm build
          # - pnpm health-check

definitions:
  caches:
    pnpm: .pnpm-store
    turbo: .turbo
