name: PNPM install & health check

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: # Enables running workflow manually    

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10  # Enforce 10-minute job timeout
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.0
        cache: 'pnpm'
    
    - name: Install dependencies
      run: |
        npm install --global corepack@latest
        corepack enable
        corepack prepare pnpm@10.9.0 --activate
        pnpm install --frozen-lockfile
        pnpm lint
        pnpm health-check
        pnpm test
        pnpm build
