name: PNPM install & health check

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: # Enables running workflow manually    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      # Add Turborepo cache
      - name: Cache Turborepo
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-          

      - name: Install dependencies
        run: |
          npm install -g pnpm@8.15.8
          pnpm install
          pnpm lint
          pnpm health-check
          pnpm test
          pnpm build